### ISSUE TITLE
Application config during dependency compilation

### ISSUE THREAD

**Issue by xanderio** [code-supply/deps_nix#6] opened 2024-11-08 10:43 UTC
As far as currently understand how `mix` handles configuration during dependency compilation, it seems wrong to me that we aren't passing the application config to the dependency derivations. This results in some strange behaviour such as `fun_with_flags` causing a runtime as it ships its own `config/config.exs` file.

I would suggest adding a `appConfigPath` parameter to the generated `deps.nix` file, which is added to all derivations. This in turn contains the path to the main application's config dir.

I've noticed this during my current attempts at packaging the plausible 2.1.x updates for nixpkgs.

**Comment by camelpunch** [comment] 2024-11-14 17:57
So can I reproduce an exception by adding plausible to a mix.exs?

**Comment by camelpunch** [comment] 2024-11-24 15:06
Looking at this today. Quite the complex set of dependencies, npm and all! Will see if I can get deps_nix working with the app, then think about how we could use deps_nix to generate nix derivations for plausible in nixpkgs.

I've used plausible casually in the past so have some skin in this game.

**Comment by xanderio** [comment] 2024-11-24 16:46
I've switch away from deps_nix for the nixpkgs package as the generated code contains `builtins.fetchGit` call which aren't allowed in nixpkgs.

**Comment by camelpunch** [comment] 2024-11-24 16:55
Ah interesting. I can look at alternatives.

I think your issue is still a thing. [I bothered Kip Cole](https://github.com/elixir-cldr/cldr_numbers/issues/49) about a lack of `prod.exs` in CLDR and I think the `appConfigPath` probably fixes that across the board.

**Comment by camelpunch** [comment] 2024-11-24 17:00
Do you have a link explaining why fetchGit is disallowed? I assume it's because SHA1s aren't reliable / full git clones are bad?

**Comment by camelpunch** [comment] 2024-11-24 19:58
ChatGPT to the rescue (Google failed me): https://discourse.nixos.org/t/fetchgit-vs-fetchgit/23325

**Comment by camelpunch** [comment] 2024-12-01 11:36
I've reproduced the problem caused by lack of `appConfigPath` by creating a new Phoenix project that depends on `fun_with_flags`, then setting the following in the application's `config/config.exs`:

```
config :fun_with_flags, :cache,
  enabled: false
```

This causes the following error when starting the app when released with `deps_nix`'s `mixNixDeps`:

```
ERROR! the application :fun_with_flags has a different value set for key :cache during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behavior than expected:

  * Compile time value was not set
  * Runtime value was set to: [enabled: false]

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.clean fun_with_flags --build"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag
```

This happens because `fun_with_flags` uses `compile_env` on the config that an app provides. Because `deps_nix` compiles dependencies independently, it can't access those compile-time settings without `appConfigPath` being set.

I'll get `deps_nix` to supply this path in its generated `deps.nix` file. Maybe it'll need a bit of work to figure out where the config dir is.

Thanks for the report!

**Closed** 2024-12-01 23:37 UTC
